### ISSUE TITLE
[BUG] Invisible rectangle on screen in the top left corner (only happened once)

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#31] opened 2020-05-23 12:53 UTC
When opening the editor an invisible rectangle was on the screen in the top left corner, I couldn't click on anything in the top left corner of my screen even after closing the editor.

The only way to fix this was to restart explorer in task manager after lowering the screen resolution and reverting back to the original resolution.

**Comment by metallicafan212** [comment] 2020-05-24 22:14
Do you have a picture of this? Some of the UI rendering code does need some cleanup/updating, so it's no surprises here lmao.

**Comment by AdamJD01** [comment] 2020-05-24 23:04
No, I don't. I'll try to get one if it happens again but will probably be hard to see because it is invisible but I knew it was there from where I couldn't click the mouse lol

**Comment by AdamJD01** [comment] 2020-06-20 11:18
This happened again but managed to get a picture of it this time after lowering the screen resolution and reverting back to the original resolution which made the rectangle visible for a few seconds before disappearing.  

<img width="200" alt="rectangle" src="https://user-images.githubusercontent.com/54454429/85200495-ce856d00-b2ef-11ea-8849-b42cff9ff47d.png">

**Comment by metallicafan212** [comment] 2020-07-07 07:41
That just seems to be a bug with windows as I cannot reproduce this at all.

The program only paints when windows decides it can paint.

I'm going to close this until either I can reproduce it or you can make it happen again (repeatable preferable)

**Closed by metallicafan212** 2020-07-07 07:41 UTC
Labels: Important, bug, question
